### ISSUE TITLE
Wrong work background job "ProcessAllImageTasksJob"

### ISSUE THREAD

**Issue by Jounik53** [VirtoCommerce/vc-module-image-tools#35]
The search for a change in the background process of generating images of different sizes occurs only in the first directory, the rest are not checked. If you run it with your hands, it works out.

I believe that the problem is in this place:
![image](https://user-images.githubusercontent.com/47387646/76309796-91681280-62de-11ea-9298-010354343bcc.png)

Because when you first go through the list of tasks, we fill in "_changeBlobs" data from the first task, with its working directory, and in the next iteration we check the variable on "null" and therefore skip filling out new data from another working directory

https://virtocommerce.atlassian.net/browse/RS-418

**Comment by yecli** [comment]
What platform version is it - v2 or v3?

**Comment by akak1977** [comment]
v3. It's for me.

**Comment by yecli** [comment]
@Jounik53
Tried to reproduce the issue with cached `_changeBlobs` with no luck on the latest image tools module version.
Used local file system as the storage (in case of the described problem I do not see any differences between the local file system and Azure storage).
Each time a regular background job is started, it instantiates **new** `BlobImagesChangesProvider` with `_changeBlobs == null` through DI. There are no singletons registered. 

So I do not see the problem here, [`GetChangeFiles` discovery function](https://github.com/VirtoCommerce/vc-module-image-tools/blob/dev/VirtoCommerce.ImageToolsModule.Data/ThumbnailGeneration/ImagesChangesProvider.cs#L30) is executed **once for every background job run** (checked in debugging).

If you're observing incorrect behavior, could you please describe it and give specific steps to reproduce? In case there are some secret connection strings, e.g. Azure blob storage, please add this sensitive info in the inner ticket: https://virtocommerce.atlassian.net/browse/VP-1650

**Comment by yecli** [comment]
Released: https://github.com/VirtoCommerce/vc-module-image-tools/releases/tag/v1.2.2

**Comment by yecli** [comment]
Caching needs to be reworked.

**Comment by yecli** [comment]
Released: https://github.com/VirtoCommerce/vc-module-image-tools/releases/tag/v1.2.3
